export enum BlockType {
  Root = "root",
  Function = "function",
  FunctionInvoke = "function_invoke",
  Expression = "expression",
  Value = "value",
  Variable = "variable",
  VarInit = "variable_init",
  VarSet = "variable_set",
  Loop = "loop",
  Conditional = "conditional",
  LogicNot = "logic_not",
  LogicJunction = "logic_junction",
  LogicComparison = "logic_comparison",
}
