/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Connector on a Block within the mixed content editor
 */
export type MixedContentEditorConnector =
  | "before"
  | "after"
  | "inputExtension"
  | "conditionalExtension"
  | "output"
  | "extender"
  | "inner"
  | "innerVariable"
  | "ifTrue"
  | "ifFalse"
