/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configuration for the mixed content editor within a kutelabs challenge
 */
export interface MixedContentEditorConfiguration {
  /**
   * Defines this editor as a mixed content editor
   */
  type: "mixed"
  /**
   * Initial blocks to be loaded into the editor
   */
  initialBlocks: (
    | (MixedContentEditorBlock & {
        coordinates: {
          [k: string]: unknown
        }
      })
    | (MixedContentEditorBlock & {
        previousBlockId: string
      })
  )[]
  /**
   * Initial blocks to be loaded into the editor
   */
  initialDrawerBlocks: MixedContentEditorBlock[]
}
/**
 * Block within the mixed content editor
 */
export interface MixedContentEditorBlock {
  /**
   * A block. Use "type" to determine the type of block
   */
  block: FunctionBlock | ExpressionBlock | ValueBlock | VariableBlock
}
/**
 * Function Block
 */
export interface FunctionBlock {
  /**
   * Defines this block as a function block
   */
  type: "function"
  /**
   * Function Block Data
   */
  data: {
    /**
     * Name of the function
     */
    name: string
  }
}
/**
 * Expression Block
 */
export interface ExpressionBlock {
  /**
   * Defines this block as an expression block
   */
  type: "expression"
  /**
   * Expression Block Data
   */
  data: {
    /**
     * Standard expression to be evaluated or Custom to use customExpression
     */
    definedExpression?: "Custom" | "Println"
    /**
     * Custom expression to be evaluated
     */
    customExpression?: {
      kt?: string
      js?: string
      [k: string]: string
    }
    editable?:
      | false
      | {
          lang: string
          linesHeight?: number
          maxLines?: number
        }
  }
}
/**
 * Value Block
 */
export interface ValueBlock {
  /**
   * Defines this block as an value block
   */
  type: "value"
  /**
   * Value Block Data
   */
  data: {
    [k: string]: unknown
  }
}
/**
 * Variable Block
 */
export interface VariableBlock {
  /**
   * Defines this block as an variable block
   */
  type: "variable"
  /**
   * Variable Block Data
   */
  data: {
    /**
     * Name of the variable
     */
    name: string
    /**
     * Variable type (from ValueDataType)
     */
    type: "int" | "float" | "string" | "boolean" | "array<int>" | "array<float>" | "array<string>" | "array<boolean>"
  }
}
